<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FolderSnippets</AssemblyName>
    <RootNamespace>FolderSnippets</RootNamespace>
    <Platforms>x64</Platforms>
    <ApplicationIcon Condition="Exists('Assets\\app.ico')">Assets\app.ico</ApplicationIcon>
    <VersionPrefix>0.1</VersionPrefix>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1</InformationalVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  

  <ItemGroup>
    <PackageReference Include="AutoHotkey.Interop" Version="1.0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\\app.ico" CopyToOutputDirectory="PreserveNewest" Condition="Exists('Assets\\app.ico')" />
  </ItemGroup>

  <Target Name="CopyVersionedExe" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(OutDir)FolderSnippets.v$(VersionPrefix).exe" />
  </Target>

</Project>
